# ######################
# SITE SETTINGS
# ######################
title: 喵落阁 # The name of your blog, used in titles and meta tags.
subTitle: 克喵的博客 # A short description that appears after the main title.
description: 克喵的博客，用于分享生活、资源和踩坑教学。 # A longer description for SEO and meta tags.
keywords: 'Suzu, Next.js, markdown blog, 克喵, blog, sakura, 克喵爱吃卤面' # Comma-separated keywords for SEO purposes.
author:
  name: 克喵爱吃老妈 # Your name, displayed as the author of the blog.
  link: 'https://www.kemiao.online' # Link to your personal website or blog.
# Language setting: Use ISO 639-1 code (e.g., 'en' for English, 'zh' for Chinese)
lang: zh
# Your public root url, used for SEO and meta tags.
# !Do not include a ending slash
siteUrl: 'http://me.kemeow.top'

# Path to your avatar image. Can be a relative path from /public or a full URL (e.g., https://).
avatar: /images/avatar.jpg
# Used as the default thumbnail for posts without thumbnails.
background: /images/background.jpg
# Slogan displayed on your homepage, under your avatar.
slogan: 愿你看清一切真相后，依旧热爱你的家人和朋友。
# Google Analytics tracking ID (e.g., 'G-XXXXXXXXXX'). Leave empty if you do not want to use Google Analytics.
googleAnalytics:

# ######################
# POSTS SETTINGS
# ######################
# How many posts you want to display per page. (default(not set): 5, max: 15)
postsPerPage:
# Your custom CC license for the posts.
creativeCommons:
  type: CC BY-SA 4.0 Deed
  link: https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans

# ######################
# HEADER SETTINGS
# ######################
# If you want to join the travellings community, set the following field to true.
# For more information, visit https://www.travellings.cn/en_US/
travellings: true

# ######################
# FOOTER SETTINGS
# ######################
# If you want to have a start year of your blog, set the year here.
startYear: 2025 # Leave empty if you do not want to display a start year.

# ######################
# PAGES SETTINGS
# ######################
# Add your AniList username if you want to display your AniList profile.
# Leave the field empty if you do not want to display your AniList profile.
anilist_username: # Your AniList username. https://anilist.co/user/username

# ######################
# SOCIAL MEDIA SETTINGS
# ######################
# Add your social media usernames.
# Leave the field empty if you do not want to display a specific platform.
# The order of the social media icons is determined by the order below.
socialMedia:
  github_username: Kemeow815 # Your GitHub username. https://github.com/username
  linkedin_username: # Your LinkedIn username. https://www.linkedin.com/in/username
  instagram_id: # Your Instagram username.
  orcid_id: # Your ORCID iD.
  telegram_username: KemiaoJun # Your Telegram username. https://t.me/username
  bluesky_username: # Your Bluesky username (without prefix). https://bsky.app/profile/{username}
  youtube_id: # Your YouTube channel ID. https://www.youtube.com/@username
  zhihu_username: # Your Zhihu username. https://www.zhihu.com/people/username
  bilibili_id: 3546643173477234 # Your Bilibili ID. https://space.bilibili.com/username
  email: me@kemiaosw.top # Your email address.
  rss: true # Display the RSS icon. Set to false to hide the icon. Set empty to fully disable the RSS feed.
  qq: p0B0Y9wNDU

# ######################
# COMMENTS SETTINGS
# Only one of the following two options should be enabled.
# Priority: Twikoo > Disqus
# ######################
# Your Twikoo environment ID.
twikooEnvId: https://twikoo-suzublog.kemeow.top
# Your Disqus shortname (used for integrating Disqus comments).
# Find this in your Disqus account: yoursite.disqus.com (shortname is the part before .disqus.com).
disqusShortname:

# ######################
# CUSTOM CODE BLOCKS
# ! WARNING: Only modify these if you understand the purpose of custom scripts.
# ######################
# Add custom JavaScript code to be included inside the <head> section of your site. One script per line.
headerJavascript:
  - https://cdn.jsdelivr.net/gh/zl-asica/web-cdn/js/zlasica.js
# Add custom HTML code to be included inside the <footer> section of your site.
slotFooter: |
  <!-- Add your custom footer HTML here -->
